networks:
  proj:

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 8080:80
    depends_on:
      - blog
    networks:
      - proj

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - proj

  blog:
    build: ./
    command: gunicorn django_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proj

volumes:
  db_data:
  static_volume: